version: '3.8'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app_moona
      - app_other

  app_moona:
    build:
      context: ./moona
    volumes:
      - ./moona/db:/app/db
      - ./moona/static:/app/static
    environment:
      - SECRET_KEY=your-secret-key
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: certonly --webroot --webroot-path=/var/www/certbot --email andrei@duvakin.com --agree-tos --no-eff-email -d moona.numerum.site
