version: '3.8'

services:
  app_moona:
    build:
      context: ./moona
    volumes:
      - ./moona/db:/app/db
      - ./moona/static:/app/static
    environment:
      - SECRET_KEY=your-secret-key
    restart: always
