apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: moona-secret
                  key: SECRET_KEY
          volumeMounts:
            - name: static-volume
              mountPath: {{ .Values.persistence.static.containerPath }}
            - name: db-volume
              mountPath: {{ .Values.persistence.db.containerPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-static-pvc"
        - name: db-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-db-pvc"