replicaCount: 1

image:
  repository: andreiduvakin/moona-diary-project
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    memory: 512Mi
    cpu: 500m

persistence:
  path: /mnt/k8s_storage/moona
  static:
    enabled: true
    size: 2Gi
  db:
    enabled: true
    size: 2Gi

ingress:
  secretTLSName: moona-tls-secret

  domain: moona.numerum.team

  path: /
  pathType: Prefix