replicaCount: 1

image:
  repository: andreiduvakin/moona-diary-project
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    memory: 128Mi
    cpu: 100m

persistence:
  path: /mnt/k8s_storage/moona
  static:
    enabled: true
    size: 2Gi
    containerPath: /app/static
  db:
    enabled: true
    size: 2Gi
    containerPath: /app/db

ingress:
  secretTLSName: moona-tls-secret

  domain: moona.numerum.team

  path: /
  pathType: Prefix